services:
  - type: web
    name: plant-disease-api
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.10.13

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn plant_api.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: plant_api.settings
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"
