services:
  - type: web
    name: plant-disease-api
    env: python
    runtime: python-3.10.13
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn plant_api.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 180
